# Generated by Django 3.2.9 on 2021-11-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_categoria_is_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='created_dt',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='update_dt',
        ),
        migrations.AddField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dt.Inclusão'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dt.Update'),
        ),
    ]
