# Generated by Django 3.2.9 on 2021-11-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_auto_20211128_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código'),
        ),
    ]
